spring-boot-primefacesx/src/main/java/th/co/cana/primefacesx/jsf/bean/WebPreferences.java
/*
* -----------------------------------------------------------------------------------
* Copyright © 2021 by Cana enterprise co,.Ltd. All rights reserved.
* -----------------------------------------------------------------------------------
*/
package th.co.cana.primefacesx.jsf.bean;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import java.util.Locale;
import java.util.Map;

import javax.annotation.PostConstruct;
import javax.enterprise.context.SessionScoped;
import javax.inject.Named;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import th.co.cana.primefacesx.jsf.theme.ThemeComponent;
import th.co.cana.primefacesx.jsf.theme.ThemeMenu;
import th.co.cana.primefacesx.jsf.theme.ThemePalette;
import th.co.cana.primefacesx.jsf.theme.ThemeTopbar;
import th.co.cana.primefacesx.jsf.theme.ThemeUtils;
import th.co.cana.primefacesx.utils.Constants;
import th.co.cana.primefacesx.utils.FacesUtils;
import th.co.cana.primefacesx.utils.PFUtils;
import th.co.cana.utils.Validators;

/**
* @author supot
* @version 1.0
*/
@Named
@SessionScoped
public class WebPreferences implements Serializable {
	private static final long serialVersionUID = 1L;
	private static final String NONE_COLOR = "transparent";
	private static final Logger logger = LoggerFactory.getLogger(WebPreferences.class);
	
	//Themes
	private String menuMode = "layout-horizontal";
	private String menuColor = "colored";
	private String menuTheme = "teallight";
	private String topbarTheme = "bluedark";
	private String inputStyle = "outlined";
    private String componentTheme = "teallight";     
	private String layoutPrimaryColor = "teallight";
    private boolean groupedMenu = true;
    private boolean darkLogo;
    private List<ThemeComponent> componentThemes;
    private List<ThemeTopbar> topbarThemes;
    private Map<String, List<ThemeMenu>> menuColors;
    private List<ThemePalette> palettes;
    private ThemePalette selectedPalette;

    //Others
	private List<String> errors;
	private List<String> jsCommands;
	private Locale locale = Constants.TH;
	
    @PostConstruct
    public void init() {
    	logger.info("Starting : {}", getClass().getName());
        componentThemes = ThemeUtils.pandoraComponents();
        topbarThemes = ThemeUtils.pandoraTopbars();
        menuColors = ThemeUtils.pandoraMenuColors();
        palettes = ThemeUtils.pandoraPalettes();
        
        //Menu: Light | Active: Teal-Light | Topbar: Teal-Light | Components: Teal-Light
        selectedPalette = palettes.get(2);
    }
    
    public String getLayoutConfig() {
        StringBuilder sb = new StringBuilder();
        String menuModeClass = ThemeUtils.getMenuModeClass(menuMode);
        String menuThemeClass = "layout-menu-" + ("colored".equals(menuColor) ? this.menuTheme : this.menuColor);

        sb.append("layout-topbar-").append(this.topbarTheme);
        sb.append(" ").append(menuThemeClass);
        sb.append(" ").append(menuModeClass);

        return sb.toString();
    }

    public void changePalette(ThemePalette palette) {
        this.setMenuColor(palette.getMenuColor().getName());
        this.setMenuTheme(palette.getMenuTheme().getName());
        this.setTopbarTheme(palette.getTopbarTheme().getName());
        this.setComponentTheme(palette.getComponentTheme().getName());
        this.setSelectedPalette(palette);
    }

	public void excuteCommand() {
		if (Validators.isEmpty(jsCommands)) {
			resetError();
			return;
		}

		for (String command : jsCommands) {
			if (Validators.isNotEmpty(command)) {
				PFUtils.execute(command);
			}
		}
		resetError();
	}
	
	public void add(String... error) {
		if (Validators.isEmpty(error)) {
			return;
		}

		if (Validators.isNull(errors)) {
			errors = new ArrayList<>();
		}
		errors.addAll(Arrays.asList(error));
	}
	
	public void addJsCommand(String ... jsCommand) {
		if (Validators.isEmpty(jsCommand)) {
			return;
		}
		
		if (Validators.isNull(jsCommands)) {
			jsCommands = new ArrayList<>();
		}
		jsCommands.addAll(Arrays.asList(jsCommand));
	}
	
	public void resetError() {
		errors = null;
		jsCommands = null;
	}
	
    /* +++++++++++++++++++++++++++++++++ Get/Set +++++++++++++++++++++++++++++++++ */
	public String getThemeName() {
		return "pandora-" + this.componentTheme;
	}
	
    public List<ThemePalette> getPalettes() {
        return palettes;
    }
    
    public String getLayout() {
        return "layout-" + this.layoutPrimaryColor;
    }

    public String getLayoutPrimaryColor() {
        return layoutPrimaryColor;
    }

    public void setLayoutPrimaryColor(String layoutPrimaryColor) {
        this.layoutPrimaryColor = layoutPrimaryColor;
    }

    public String getTopbarTheme() {
        return topbarTheme;
    }

    public boolean isDarkLogo() {
        return this.darkLogo;
    }
    
    public void setTopbarTheme(String topbarTheme) {
        this.topbarTheme = topbarTheme;
        this.darkLogo = "light".equals(this.topbarTheme);
        this.setSelectedPalette(null);
    }

    public String getComponentTheme() {
        return componentTheme;
    }

    public void setComponentTheme(String componentTheme) {
        this.componentTheme = componentTheme;
        this.setSelectedPalette(null);
    }

    public String getMenuMode() {
        return menuMode;
    }

    public void setMenuMode(String menuMode) {
        this.menuMode = menuMode;
    }

    public String getMenuColor() {
        return menuColor;
    }

	public void setMenuColor(String menuColor) {
		try {
			this.menuColor = menuColor;
			this.menuTheme = this.menuColors.get(menuColor).get(0).getFile();
			this.setSelectedPalette(null);
		} catch (Exception ex) {
			//ignore error
		}
	}

    public String getMenuTheme() {
        return menuTheme;
    }

    public void setMenuTheme(String menuTheme) {
        this.menuTheme = menuTheme;
        this.setSelectedPalette(null);
    }

    public String getInputStyle() {
        return inputStyle;
    }

    public void setInputStyle(String inputStyle) {
        this.inputStyle = inputStyle;
    }

    public String getInputStyleClass() {
        return ThemeUtils.getInputStyleClass(inputStyle);
    }

    public boolean isGroupedMenu() {
        return this.groupedMenu;
    }

    public void setGroupedMenu(boolean value) {
        this.groupedMenu = value;
    }
    
    public List<ThemeComponent> getComponentThemes() {
        return componentThemes;
    }
    
    public List<ThemeTopbar> getTopbarThemes() {
        return topbarThemes;
    }
    
    public Map<String, List<ThemeMenu>> getMenuColors() {
        return menuColors;
    }

	public List<ThemeMenu> getThemeMenuItems() {
		if (Validators.isEmpty(menuColors)) {
			return Collections.emptyList();
		}
		return menuColors.get(menuColor);
	}
    
    public ThemePalette getSelectedPalette() {
        return selectedPalette;
    }

    public void setSelectedPalette(ThemePalette selectedPalette) {
        this.selectedPalette = selectedPalette;
    }
    
	public List<String> getErrors() {
		return errors;
	}

	public void setErrors(List<String> errors) {
		this.errors = errors;
	}
	
	public List<String> getJsCommands() {
		return jsCommands;
	}

	public void setJsCommands(List<String> jsCommands) {
		this.jsCommands = jsCommands;
	}

	public Locale getLocale() {
		if (locale == null) {
			locale = FacesUtils.getLocale();
		}
		return locale;
	}

	public void setLocale(Locale locale) {
		this.locale = locale;
	}
	
	public String getMenuBgColor() {
		return (selectedPalette != null ? selectedPalette.getMenuColor().getCode() : NONE_COLOR);
	}
	
	public String getMenuTitle() {
		return (selectedPalette != null ? selectedPalette.getMenuColor().getName() : "");
	}
	
	public String getThemeBgColor() {
		return (selectedPalette != null ? selectedPalette.getMenuTheme().getCode() : NONE_COLOR);
	}
	
	public String getThemeTitle() {
		return (selectedPalette != null ? selectedPalette.getMenuTheme().getName() : "");
	}
	
	public String getTopbarBgColor() {
		return (selectedPalette != null ? selectedPalette.getTopbarTheme().getCode() : NONE_COLOR);
	}
	
	public String getTopbarTitle() {
		return (selectedPalette != null ? selectedPalette.getTopbarTheme().getName() : "");
	}
	
	public String getComponentBgColor() {
		return (selectedPalette != null ? selectedPalette.getComponentTheme().getCode() : NONE_COLOR);
	}
	
	public String getComponentTitle() {
		return (selectedPalette != null ? selectedPalette.getComponentTheme().getName() : "");
	}
	
	public boolean isEmptyError() {
		return (errors == null || errors.isEmpty());
	}
	
	public boolean isOneItem() {
		return (errors != null && errors.size() == 1);
	}
	
	public boolean isLangThai() {
		return FacesUtils.isLangThai();
	}
	
	public boolean isValidationFailed() {
		return (FacesUtils.getMaximumSeverity() != null || FacesUtils.isValidationFailed()) 
				&& !FacesUtils.isEmptyError() && isEmptyError();
	}
}

spring-boot-primefacesx/src/main/webapp/WEB-INF/templates/inc-ajax-status.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui">

	<p:ajaxStatus styleClass="ajax-status-centered" widgetVar="ajaxStatusVar">
		<f:facet name="start">
			<i class="fa fa-circle-o-notch fa-spin ajax-status-icon" aria-hidden="true"></i>
		</f:facet>
		<f:facet name="complete">
			<h:outputText value="" />
		</f:facet>
	</p:ajaxStatus>
</ui:composition>

spring-boot-primefacesx/src/main/webapp/WEB-INF/templates/inc-confirm-dialog.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:pe="http://primefaces.org/ui/extensions">

	<p:confirmDialog global="true" showEffect="fade" hideEffect="fade"
		widgetVar="mainConfirmDialog" header="#{msg['msg.confirm.title']}"
		message="#{msg['msg.confirm.info']}" responsive="true">
		
		<h:panelGroup layout="block" styleClass="center" style="margin-top:10px;">
			<p:commandButton value="#{msg['msg.button.yes']}" type="button"
				styleClass="ui-confirmdialog-yes"
				icon="fa fa-check">
			</p:commandButton>
			<p:commandButton value="#{msg['msg.button.no']}" 
				type="button"
				styleClass="ui-confirmdialog-no ui-button-danger"
				style="margin-left:15px;"
				icon="fa fa-times">
			</p:commandButton>
		</h:panelGroup>
	</p:confirmDialog>
</ui:composition>

spring-boot-primefacesx/src/main/webapp/WEB-INF/templates/menu-group.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:p="http://primefaces.org/ui"
	xmlns:po="http://primefaces.org/pandora">

	<po:menu widgetVar="PandoraMenuWidget">
		<p:menuitem value="#{msg['menu.dashboard']}"
			action="#{menuCtrl.changePageAction('DASHBOARD')}" icon="pi pi-fw pi-sitemap"
			immediate="true">
		</p:menuitem>
		<p:menuitem value="#{msg['menu.home']}"
			action="#{menuCtrl.changePageAction('HOME')}" icon="pi pi-fw pi-home"
			immediate="true">
		</p:menuitem>
		<p:menuitem value="#{msg['menu.session']}"
			action="#{menuCtrl.changePageAction('SESSION')}"
			icon="pi pi-fw pi-book" immediate="true">
		</p:menuitem>
		<p:menuitem value="#{msg['menu.view']}"
			action="#{menuCtrl.changePageAction('VIEW')}" icon="pi pi-fw pi-book"
			immediate="true">
		</p:menuitem>
	</po:menu>

</ui:composition>

spring-boot-primefacesx/src/main/webapp/WEB-INF/templates/menu-ungrouped.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:p="http://primefaces.org/ui"
	xmlns:po="http://primefaces.org/pandora">

	<po:menu widgetVar="PandoraMenuWidget">
		<p:submenu id="om_homepage" label="Main Menu" icon="pi pi-fw pi-home">
			<p:menuitem value="#{msg['menu.dashboard']}"
				action="#{menuCtrl.changePageAction('DASHBOARD')}" icon="pi pi-fw pi-sitemap"
				immediate="true">
			</p:menuitem>
			<p:menuitem value="#{msg['menu.home']}"
				action="#{menuCtrl.changePageAction('HOME')}"
				icon="pi pi-fw pi-home" immediate="true">
			</p:menuitem>
			<p:menuitem value="#{msg['menu.session']}"
				action="#{menuCtrl.changePageAction('SESSION')}"
				icon="pi pi-fw pi-book" immediate="true">
			</p:menuitem>
			<p:menuitem value="#{msg['menu.view']}"
				action="#{menuCtrl.changePageAction('VIEW')}"
				icon="pi pi-fw pi-book" immediate="true">
			</p:menuitem>
		</p:submenu>
	</po:menu>

</ui:composition>

spring-boot-primefacesx/src/main/webapp/WEB-INF/templates/system-breadcrumb.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">

	<div class="layout-breadcrumb">
		<div class="breadcrumb">
			<div class="breadcrumb-icon">
				<i class="pi pi-sitemap" aria-hidden="true"/>
			</div>
			<div class="route-bar-breadcrumb">
				<ui:insert name="viewname" />
			</div>
		</div>
	</div>

</ui:composition>

spring-boot-primefacesx/src/main/webapp/WEB-INF/templates/system-footer.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">

	<div class="layout-footer">
		<p:graphicImage name="images/logo-footer.svg" styleClass="topbar-logo"/>
		<div class="social-icons">
			<a><i class="pi pi-facebook" aria-hidden="true"/></a>
			<a><i class="pi pi-twitter" aria-hidden="true"/></a>
		</div>
	</div>
</ui:composition>

spring-boot-primefacesx/src/main/webapp/WEB-INF/templates/system-rightpanel.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">

	<div class="layout-rightpanel">
		<div class="rightpanel-wrapper">
			<div class="rightpanel-header">
				<div class="cover">
					<p:graphicImage name="images/profile-cover1.jpg" styleClass="cover-image"/>
					<p:graphicImage name="images/icons/admin.svg" styleClass="avatar-image" />
				</div>
				<div class="profile-info">
					<h4>#{userInfo.fullName}</h4>
					<span class="status p-mt-2">Role: #{userInfo.role}</span>
					<ul class="no-bullets p-mt-2">
						<li>
							<p:commandLink immediate="true"> 
								<i class="pi pi-fw pi-user icon" aria-hidden="true"/> #{msg['menu.profile']}
							</p:commandLink>
						</li>
						<li>
							<p:commandLink immediate="true"> 
								<i class="pi pi-fw pi-cog icon" aria-hidden="true"/> #{msg['menu.settings']}
							</p:commandLink>
						</li>
						<li>
							<p:commandLink immediate="true"> 
								<i class="pi pi-fw pi-sign-out icon fa-red" aria-hidden="true"/> #{msg['menu.logout']}
							</p:commandLink>
						</li>
					</ul>
				</div>
			</div>

			<div class="rightpanel-graph">
				<h4>#{msg['dashboard.user.activity.summary']}</h4>
				<div class="graph-content">
					<div class="graph-wrapper">
						<div class="graph-item">40%</div>
						<div class="graph-item">20%</div>
						<div class="graph-item">25%</div>
						<div class="graph-item">15%</div>
					</div>
					<ul>
						<li><span><span class="label-color"></span>#{msg['dashboard.user.meeting']}</span></li>
						<li><span><span class="label-color"></span>#{msg['dashboard.user.event']}</span></li>
						<li><span><span class="label-color"></span>#{msg['dashboard.user.course']}</span></li>
						<li><span><span class="label-color"></span>#{msg['dashboard.user.assessment']}</span></li>
					</ul>
				</div>
			</div>
		</div>
	</div>

</ui:composition>

spring-boot-primefacesx/src/main/webapp/WEB-INF/templates/system-topbar.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">

	<div class="layout-topbar">
		<div class="layout-topbar-wrapper">
			<ui:remove> +++++++++++++ Logo +++++++++++++++++ </ui:remove>
			<div class="layout-topbar-left">
				<div class="menu-button">
					<i class="pi pi-bars" aria-hidden="true"/>
				</div>
				<h:link id="logolink" class="layout-topbar-logo">
					<p:graphicImage name="images/#{webPreferences.darkLogo ? 'logo-pandora.svg' : 'logo-pandora.svg'}" styleClass="topbar-logo"/>
				</h:link>
			</div>
			
			<div class="layout-topbar-right">
				<ul class="layout-topbar-actions">
					<li class="topbar-item notifications">
						<a href="#"> 
							<i class="topbar-icon pi pi-bell" aria-hidden="true"><span class="dot"></span></i>
						</a>
						<ul>
							<li class="layout-submenu-header">
								<h4 class="header-text">Notifications</h4> 
							</li>
							<li class="layout-submenu-item">
								<div class="menu-text">
									<i class="fa fa-users" aria-hidden="true"/>
									<div>
										<p>Meeting transaction 10</p>
									</div>
								</div>
							</li>
							<li class="layout-submenu-item">
								<div class="menu-text">
									<i class="fa fa-fw fa-book" aria-hidden="true"/>
									<div>
										<p>Event transaction 11</p>
									</div>
								</div>
							</li>
							<li class="layout-submenu-item">
								<div class="menu-text">
									<i class="fa fa-fw fa-book" aria-hidden="true"/>
									<div>
										<p>Course transaction 11</p>
									</div>
								</div>
							</li>
						</ul>
					</li>
					<li class="topbar-item-v-separator" />
				</ul>
			</div>
			
			<a href="#" class="layout-rightpanel-button"> 
				<p:graphicImage name="images/icons/admin.svg" /> 
			</a>
		</div>
	</div>

</ui:composition>

spring-boot-primefacesx/src/main/webapp/WEB-INF/templates/sytem-menu.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">

	<div class="menu-wrapper">
		<div class="layout-menu-container">
			<h:form id="menuform">				
				<ui:remove>+++++++++++++++++++++ Menu Mode +++++++++++++++++++++++++ </ui:remove>
				<ui:include src="#{webPreferences.groupedMenu ? 'menu-group.xhtml' : 'menu-ungrouped.xhtml'}" />
			</h:form>
		</div>
	</div>

</ui:composition>

spring-boot-primefacesx/src/main/webapp/WEB-INF/templates/template.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:p="http://primefaces.org/ui" lang="th">

<f:view contentType="text/html" locale="#{webPreferences.locale}">
	<h:head>
		<f:facet name="first">
			<meta http-equiv="X-UA-Compatible" content="IE=edge" />
			<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
			<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" />
			<meta name="apple-mobile-web-app-capable" content="yes" />
		</f:facet>
		<title><ui:insert name="title">#{msg['msg.app.name']}</ui:insert></title>
		
		<h:outputScript name="pandora-layout/js/layout.js" />
		<h:outputScript name="pandora-layout/js/prism.js" />
		
		<ui:insert name="head" />
	</h:head>

	<h:body styleClass="#{webPreferences.inputStyleClass}">
		<div class="layout-wrapper #{webPreferences.layoutConfig}">

			<ui:include src="system-rightpanel.xhtml" />
			<ui:include src="sytem-menu.xhtml" />

			<div class="layout-main">
				<ui:include src="system-topbar.xhtml" />
				<h:panelGroup rendered="false">
					<ui:include src="system-breadcrumb.xhtml" />
				</h:panelGroup>
				
				<div class="layout-content">
					<ui:include src="inc-ajax-status.xhtml" />
					<ui:include src="inc-confirm-dialog.xhtml" />
				
					<ui:insert name="content" />
					<ui:insert name="popup" />
				</div>

				<ui:include src="system-config.xhtml" />
				<ui:include src="system-footer.xhtml" />
				
				<div class="layout-mask"></div>
			</div>
		</div>

		<h:outputStylesheet name="pandora-layout/css/primeicons.css" />
		<h:outputStylesheet name="pandora-layout/css/primeflex.min.css" />
		<h:outputStylesheet name="pandora-layout/css/#{webPreferences.layout}.css" />
        <h:outputStylesheet name="css/style-font.css" />
        <h:outputStylesheet name="css/style-pandora.css" />
        <h:outputStylesheet name="css/style-resp.css" />
        <h:outputStylesheet name="css/style-required.css" />
        
	</h:body>
</f:view>
</html>